version: '{branch}.{build}'
skip_non_tags: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
nuget:
  disable_publish_on_pr: true
before_build:
- ps: >-
    dotnet restore ConsistentHash.csproj --verbosity m;
    dotnet restore Tests/ConsistentHashTests.csproj --verbosity m;
build:
  project: ConsistentHash.csproj
  publish_nuget: true
  verbosity: minimal
test_script:
- ps: dotnet test Tests/ConsistentHashTests.csproj --test-adapter-path:. --logger:Appveyor
deploy:
- provider: NuGet
  api_key:
    secure: +AfUqfg+JvLrMo8kT0f3adRuOvj+2LaEj3Y2q8zl55Uqx2JU6JujCZIF7gS4WLqq
  on:
    APPVEYOR_REPO_TAG: true